# Use a specific version tag for better reproducibility
FROM hashicorp/terraform:1.9

# Set environment variables
ENV TERRAPI_PLATFORM=terraform

# Copy the binary to the appropriate directory
COPY bin/terrapi-worker /usr/bin/terrapi-worker

# Ensure the binary has execute permissions
RUN chmod +x /usr/bin/terrapi-worker

# Set the entrypoint
ENTRYPOINT ["/usr/bin/terrapi-worker"]