# Use a specific version tag for better reproducibility
FROM --platform=linux/arm/v6 ghcr.io/opentofu/opentof:1.8

# Set environment variables
ENV TERRAPI_PLATFORM=opentofu

# Copy the binary to the appropriate directory
COPY bin/terrapi-worker /usr/binterrapi-worker

# Ensure the binary has execute permissions
RUN chmod +x /usr/local/bin/terrapi-worker

# Set the entrypoint
ENTRYPOINT ["/usr/bin/terrapi-worker"]