# Use a specific version tag for better reproducibility
FROM ghcr.io/opentofu/opentofu:1.8.3-arm64

# Set environment variables
ENV TERRAPI_PLATFORM=opentofu

# Copy the binary to the appropriate directory
COPY bin/terrapi-runner /usr/bin/terrapi-runner

# Ensure the binary has execute permissions
RUN chmod +x /usr/bin/terrapi-runner

# Set the entrypoint
ENTRYPOINT ["/usr/bin/terrapi-runner"]