---
name: docker

"on":
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - target: terraform
            platform: linux/386
            goos: linux
            goarch: 386
          - target: terraform
            platform: linux/amd64
            goos: linux
            goarch: amd64
          - target: terraform
            platform: linux/arm64
            goos: linux
            goarch: arm64
          - target: terraform
            platform: linux/arm/6
            goos: linux
            goarch: arm
            goarm: 6
          - target: openbao
            platform: linux/386
            goos: linux
            goarch: 386
          - target: openbao
            platform: linux/amd64
            goos: linux
            goarch: amd64
          - target: openbao
            platform: linux/arm64
            goos: linux
            goarch: arm64
          - target: openbao
            platform: linux/arm/6
            goos: linux
            goarch: arm
            goarm: 6

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup golang
        id: golang
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23.0

      - name: Run generate
        id: generate
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: make generate

      - name: Run build
        id: build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOARM: ${{ matrix.goarm }}
        run: make build

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            thomas-illiet/terrapi-worker
            quay.io/thomas-illiet/terrapi-worker
            ghcr.io/thomas-illiet/terrapi-worker
          labels: |
            org.opencontainers.image.vendor=Thomas ILLIET
            maintainer=Thomas ILLIET <contact@thomas-illiet.fr>
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            suffix=-${{ matrix.target }}-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Setup qemu
        id: qemu
        uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        id: publish
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          provenance: false
          file: docker/Dockerfile.${{ matrix.target }}.${{ matrix.goos }}.${{ matrix.goarch }}
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}